# Generated by Django 5.0.6 on 2024-05-20 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EliteDownload', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'file', 'verbose_name_plural': 'files'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
